### ISSUE TITLE
`pod install` is failing

### ISSUE THREAD

**Issue by apicgg** [react-native-maps/react-native-maps#5466]
### Summary

While trying to upgrade the lib from version `1.20.1` to `1.22.6` because of the new architecture support, the `pod install` step is failing.

### Reproducible sample code

```TSX
npm install react-native-maps
```

### Steps to reproduce

- Install the latest npm package via `npm install react-native-maps`.
- Run `npx pod-install`.
- See the error while installing with `pod install`.

### Expected result

The `pod install` step should install the native modules.

### Actual result

`pod install` is failing. See the below errors.

<img width="1225" alt="Image" src="https://github.com/user-attachments/assets/43401932-f678-4a37-a7cf-08d061f67a9d" />

<img width="1227" alt="Image" src="https://github.com/user-attachments/assets/95785a61-65e7-487b-9434-837761e661c1" />

### React Native Maps Version

1.22.6

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.77.2

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 16

**Comment by russmenum** [comment]
@apicgg I can help you with the pod, but still may not work

add ```pod 'react-native-maps-generated', :path => rn_maps_path``` aka
```
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'react-native-maps-generated', :path => rn_maps_path
```
instead of 
```
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
```
from the doc, for whatever reason, the install instructions left that step off

But, depending on the specifics of your project may still not work. I think the cases where it won't work are if you have ```use_frameworks!```, but it may not be, I have open issues to try and see what the problem is after you get past this problem.

Hopfuly for your app, adding the required pod will get you going

**Comment by salah-ghanim** [comment]
you don't need the patch anymore, if you use https://github.com/react-native-maps/react-native-maps/releases/tag/v1.23.0 it should work out of the box.

**Comment by bitcrumb** [comment]
I am now getting TypeScript errors after upgrading to 1.23.0:

```
daikin-onecta-app on  renovate/react-native-maps-1.x [$!] via  v22.14.0 via 💎 v3.3.5 on ☁️  lode@inthepocket.com 
❯ npx tsc     
node_modules/react-native-maps/src/AnimatedRegion.ts:92:11 - error TS6133: '__attach' is declared but its value is never read.

92   private __attach() {
             ~~~~~~~~

node_modules/react-native-maps/src/AnimatedRegion.ts:99:11 - error TS6133: '__detach' is declared but its value is never read.

99   private __detach() {
             ~~~~~~~~

node_modules/react-native-maps/src/decorateMapComponent.ts:160:7 - error TS2322: Type 'NativeComponent<unknown> | undefined' is not assignable to type 'NativeComponent<unknown>'.
  Type 'undefined' is not assignable to type 'NativeComponent<unknown>'.

160       return components[key];
          ~~~~~~

node_modules/react-native-maps/src/decorateMapComponent.ts:170:5 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

170     return UIManager.getViewManagerConfig(nativeComponentName).Commands[name];
        ~~~~~~

node_modules/react-native-maps/src/Geojson.tsx:388:5 - error TS2322: Type 'LatLng[] | undefined' is not assignable to type 'LatLng[]'.
  Type 'undefined' is not assignable to type 'LatLng[]'.

388     coordinates: coordinates[0],
        ~~~~~~~~~~~

  node_modules/react-native-maps/src/Geojson.tsx:532:3
    532   coordinates: LatLng[];
          ~~~~~~~~~~~
    The expected type comes from property 'coordinates' which is declared here on type 'Omit<AnyPolygonOverlay, "type">'

node_modules/react-native-maps/src/Geojson.tsx:394:3 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

394   latitude: c[1],
      ~~~~~~~~

  node_modules/react-native-maps/src/sharedTypes.ts:6:3
    6   latitude: number;
        ~~~~~~~~
    The expected type comes from property 'latitude' which is declared here on type 'LatLng'

node_modules/react-native-maps/src/Geojson.tsx:395:3 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

395   longitude: c[0],
      ~~~~~~~~~

  node_modules/react-native-maps/src/sharedTypes.ts:7:3
    7   longitude: number;
        ~~~~~~~~~
    The expected type comes from property 'longitude' which is declared here on type 'LatLng'

node_modules/react-native-maps/src/MapOverlay.tsx:82:27 - error TS2532: Object is possibly 'undefined'.

82     northEast: {latitude: bounds[0][0], longitude: bounds[0][1]},
                             ~~~~~~~~~

node_modules/react-native-maps/src/MapOverlay.tsx:82:52 - error TS2532: Object is possibly 'undefined'.

82     northEast: {latitude: bounds[0][0], longitude: bounds[0][1]},
                                                      ~~~~~~~~~

node_modules/react-native-maps/src/MapOverlay.tsx:83:27 - error TS2532: Object is possibly 'undefined'.

83     southWest: {latitude: bounds[1][0], longitude: bounds[1][1]},
                             ~~~~~~~~~

node_modules/react-native-maps/src/MapOverlay.tsx:83:52 - error TS2532: Object is possibly 'undefined'.

83     southWest: {latitude: bounds[1][0], longitude: bounds[1][1]},
                                                      ~~~~~~~~~

node_modules/react-native-maps/src/MapView.tsx:1041:11 - error TS6133: '_getHandle' is declared but its value is never read.

1041   private _getHandle() {
               ~~~~~~~~~~


Found 12 errors in 5 files.

Errors  Files
     2  node_modules/react-native-maps/src/AnimatedRegion.ts:92
     2  node_modules/react-native-maps/src/decorateMapComponent.ts:160
     3  node_modules/react-native-maps/src/Geojson.tsx:388
     4  node_modules/react-native-maps/src/MapOverlay.tsx:82
     1  node_modules/react-native-maps/src/MapView.tsx:1041
```
