### ISSUE TITLE
Doesn't work with React Native 0.77 or above: ViewManagerWithGeneratedInterface

### ISSUE THREAD

**Issue by akosiakevych** [react-native-maps/react-native-maps#5809]
### Summary

I have build error on android with react-native-maps: 1.26.18 and react-native: 0.77.3 with new architecture enabled, the maps using old interface `ViewManagerWithGeneratedInterface` that was moved in React Native 0.77 or above.
Error I have:

`react-native-maps/android/src/main/java/com/facebook/react/viewmanagers/RNMapsCircleManagerInterface.java:17: error: cannot find symbol
public interface RNMapsCircleManagerInterface<T extends View> extends ViewManagerWithGeneratedInterface { ^ symbol: class ViewManagerWithGeneratedInterface
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
18 errors FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'.`

### Reproducible sample code

```TSX
N/a
```

### Steps to reproduce

Install react-native-maps@latest with react-native: 0.77.3 or above and new architecture enabled
build android app
observe build error

### Expected result

Build successful 

### Actual result

Build error 

### React Native Maps Version

1.26.18

### What platforms are you seeing the problem on?

Android

### React Native Version

0.77.3

### What version of Expo are you using?

Not using Expo

### Device(s)

N/A

**Comment by akosiakevych** [comment]
Who has the same issue, I was able to resolve this by using `react-native-maps: 1.26.0`, in `1.26.1` they introduce `ViewManagerWithGeneratedInterface` dependency

**Comment by mark-zacharias** [comment]
I ran into the same error using "react-native": "0.77.1" and "react-native-maps": "^1.26.19".
I have just moved over to using expo managed.  I'll try upgrading to the latest react native to see if that changes.

**Comment by HamidAliSE** [comment]
I am also facing the same issue when upgrading my project from 0.70.1 to 0.75.5.
Any update on this?

**Comment by HamidAliSE** [comment]
@akosiakevych Can you please share your package.json.

**Comment by stanislav-sidorov** [comment]
<img width="496" height="420" alt="Image" src="https://github.com/user-attachments/assets/f1c16e41-43c9-485c-a440-8b19398ffd77" />
