### ISSUE TITLE
Issue after version update, android map never ready

### ISSUE THREAD

**Issue by ajouve** [react-native-maps/react-native-maps#5490]
### Summary

I just updated react-native to `0.79.2` and react-native-maps to `1.23.7` and I kept `newArchEnabled=false` to prevent issues with another module.

On iOS my code works fine but on android the map shows, but the markers are not rendered, and the focus does not go to `initialRegion` but it is on latitude and longitude 0

### Reproducible sample code

```TSX
import React from 'react';
import MapView, { Marker, PROVIDER_GOOGLE } from 'react-native-maps';

const Map = forwardRef(({ }, ref) => {

    return (
        <MapView
            ref={ref}
            provider={PROVIDER_GOOGLE}
            initialRegion={{ latitude: 48.8584, longitude: 2.2945, latitudeDelta: 0.05, longitudeDelta: 0.05 }}
        >
            <Marker coordinate={{ latitude: 48.8584, longitude: 2.2945 }} />
        </MapView>
    );

})
```

### Steps to reproduce

Run the code on react native `0.79.2` and react-native-maps `1.23.7`

### Expected result

The map should be displayed on `initialRegion` position and the marker should shown

### Actual result

The map is initially in 0,0 and no marker is shown.
I can drag it, the map is not frozen

### React Native Maps Version

1.23.7

### What platforms are you seeing the problem on?

Android

### React Native Version

0.79.2

### What version of Expo are you using?

Not using Expo

### Device(s)

Emulator Pixel 7 pro API 34

### Additional information

I also tried to add `onMapReady ` but never called, `onLayout` is called

I tried to add a code to manually call `onMapReady`

```
    const manuallyTriggerMapReady = async () => {
        const mapInstance = ref.current;
        if (mapInstance && mapInstance._onMapReady) {
            await mapInstance._onMapReady(); // Force trigger
            console.log('✅ Manually triggered map ready');
        }
    };

    useEffect(() => {
        setTimeout(() => {
            console.log('⏳ Entered map ready fallback effect');
            if (Platform.OS === 'android') {
                manuallyTriggerMapReady();
            }
        }, 2000); // Delay allows native map to mount
    }, []);
```

But I have an error 

- Invariant Violation: Event cannot be both direct and bubbling: topSelect
- TypeError: _reactNative.BackHandler.removeEventListener is not a function (it is undefined)

If I am not forcing onMapReady I have no error nor warning

**Comment by dpkthapa** [comment]
Same here.

**Comment by ajouve** [comment]
@narayanlava thanks I already tried a timeout before adding the marker but it did not worked

**Comment by ivan-moego** [comment]
same problem

**Comment by Souverain08** [comment]
I have the same problem, but I am using React Native version 0.76.9 and React-native-maps version 1.22.0

**Comment by CostasCF** [comment]
same issue

**Comment by tomtom83870** [comment]
Same problem with react native 0.79.2 and react-native-maps 1.23.8 no matter newArchEnabled is true or false

**Comment by DanielOnramp** [comment]
I have the same issue after upgrading from Expo 51 to 52, React native from `0.74.5` to `0.76.9" and react-native-maps from `1.14.0` to `1.18.0`

When animating to a new map region, my markers appear but the background map tiles do not appear, its blank until i move the map again manually.

**Comment by mishkeTz** [comment]
Any updates on this? Facing same issue

**Comment by salah-ghanim** [comment]
please read https://github.com/react-native-maps/react-native-maps?tab=readme-ov-file#compatibility

v1.21 (latest better) should be used with newArch
previous versions without newArch

don't expect the library to work if you don't use the correct versions

**Comment by narayanlava** [comment]
Please update podfile as below

 rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => rn_maps_path
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'react-native-maps-generated', :path => rn_maps_path
