### ISSUE TITLE
Xcode pod install undefined method `get_folly_config'

### ISSUE THREAD

**Issue by Weever** [react-native-maps/react-native-maps#5438]
### Summary

in iOS project
when update version form "1.20.1" to "1.22.5",
I delete yarn.lock, and yarn install, and pod install

pod install error, if I miss something config?

```
[!] Invalid `Podfile` file: 
[!] Invalid `react-native-maps.podspec` file: undefined method `get_folly_config' for Pod:Module.

 #  from /Users/project/node_modules/react-native-maps/react-native-maps.podspec:4
 #  -------------------------------------------
 #  
 >  folly_config = get_folly_config()
 #  folly_compiler_flags = folly_config[:compiler_flags]
 #  -------------------------------------------
```

diff map version
```
 react-native-maps@^1.13.2:
-  version "1.20.1"
-  resolved "https://registry.npmmirror.com/react-native-maps/-/react-native-maps-1.20.1.tgz#f613364886b2f72db56cafcd2bd7d3a35f470dfb"
-  integrity sha512-NZI3B5Z6kxAb8gzb2Wxzu/+P2SlFIg1waHGIpQmazDSCRkNoHNY4g96g+xS0QPSaG/9xRBbDNnd2f2/OW6t6LQ==
+  version "1.22.5"
+  resolved "https://registry.npmmirror.com/react-native-maps/-/react-native-maps-1.22.5.tgz#a65b9c5d1cd548def4a3ba9c8981a2a7ff0cc02b"
+  integrity sha512-m+p8HgqYsxAONIXDX6Ja2ATDnytzcVHoD/D86k+rIPqfAr+jL2JPzkWju0sGXnX83fnbTRfP+hPF8HSSnV4oMg==
   dependencies:
     "@types/geojson" "^7946.0.13"
```

### Reproducible sample code

```TSX
none
```

### Steps to reproduce

none

### Expected result

pod install success

### Actual result

```
[!] Invalid `Podfile` file: 
[!] Invalid `react-native-maps.podspec` file: undefined method `get_folly_config' for Pod:Module.
```

### React Native Maps Version

1.22.5

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

v0.72.5

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhoneX

**Comment by salah-ghanim** [comment]
@Weever please don't use those versions, the build is broken while trying to fix the autolinking.

soon a new version will be released that will be back to normal and include fixes to how the generated pod is linked.

**Comment by Weever** [comment]
but my app minimum deployments iOS13，'1.22.5' need iOS 15

**Comment by Saad962404** [comment]
Same error, when upgraded from 67 => 71

**Comment by jkirira** [comment]
@salah-ghanim Hello, Was this fixed in a new version?
