### ISSUE TITLE
TypeScript issue in 1.23.0

### ISSUE THREAD

**Issue by bitcrumb** [react-native-maps/react-native-maps#5479]
### Summary

I am suddently getting these TypeScript errors after upgrading to 1.23.0. These didn't used to be there in 1.20.1 (the previous version I was using). I can't use 1.22.0 since that is giving Cocoapods issues.

```
❯ npx tsc     
node_modules/react-native-maps/src/AnimatedRegion.ts:92:11 - error TS6133: '__attach' is declared but its value is never read.

92   private __attach() {
             ~~~~~~~~

node_modules/react-native-maps/src/AnimatedRegion.ts:99:11 - error TS6133: '__detach' is declared but its value is never read.

99   private __detach() {
             ~~~~~~~~

node_modules/react-native-maps/src/decorateMapComponent.ts:160:7 - error TS2322: Type 'NativeComponent<unknown> | undefined' is not assignable to type 'NativeComponent<unknown>'.
  Type 'undefined' is not assignable to type 'NativeComponent<unknown>'.

160       return components[key];
          ~~~~~~

node_modules/react-native-maps/src/decorateMapComponent.ts:170:5 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

170     return UIManager.getViewManagerConfig(nativeComponentName).Commands[name];
        ~~~~~~

node_modules/react-native-maps/src/Geojson.tsx:388:5 - error TS2322: Type 'LatLng[] | undefined' is not assignable to type 'LatLng[]'.
  Type 'undefined' is not assignable to type 'LatLng[]'.

388     coordinates: coordinates[0],
        ~~~~~~~~~~~

  node_modules/react-native-maps/src/Geojson.tsx:532:3
    532   coordinates: LatLng[];
          ~~~~~~~~~~~
    The expected type comes from property 'coordinates' which is declared here on type 'Omit<AnyPolygonOverlay, "type">'

node_modules/react-native-maps/src/Geojson.tsx:394:3 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

394   latitude: c[1],
      ~~~~~~~~

  node_modules/react-native-maps/src/sharedTypes.ts:6:3
    6   latitude: number;
        ~~~~~~~~
    The expected type comes from property 'latitude' which is declared here on type 'LatLng'

node_modules/react-native-maps/src/Geojson.tsx:395:3 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

395   longitude: c[0],
      ~~~~~~~~~

  node_modules/react-native-maps/src/sharedTypes.ts:7:3
    7   longitude: number;
        ~~~~~~~~~
    The expected type comes from property 'longitude' which is declared here on type 'LatLng'

node_modules/react-native-maps/src/MapOverlay.tsx:82:27 - error TS2532: Object is possibly 'undefined'.

82     northEast: {latitude: bounds[0][0], longitude: bounds[0][1]},
                             ~~~~~~~~~

node_modules/react-native-maps/src/MapOverlay.tsx:82:52 - error TS2532: Object is possibly 'undefined'.

82     northEast: {latitude: bounds[0][0], longitude: bounds[0][1]},
                                                      ~~~~~~~~~

node_modules/react-native-maps/src/MapOverlay.tsx:83:27 - error TS2532: Object is possibly 'undefined'.

83     southWest: {latitude: bounds[1][0], longitude: bounds[1][1]},
                             ~~~~~~~~~

node_modules/react-native-maps/src/MapOverlay.tsx:83:52 - error TS2532: Object is possibly 'undefined'.

83     southWest: {latitude: bounds[1][0], longitude: bounds[1][1]},
                                                      ~~~~~~~~~

node_modules/react-native-maps/src/MapView.tsx:1041:11 - error TS6133: '_getHandle' is declared but its value is never read.

1041   private _getHandle() {
               ~~~~~~~~~~


Found 12 errors in 5 files.

Errors  Files
     2  node_modules/react-native-maps/src/AnimatedRegion.ts:92
     2  node_modules/react-native-maps/src/decorateMapComponent.ts:160
     3  node_modules/react-native-maps/src/Geojson.tsx:388
     4  node_modules/react-native-maps/src/MapOverlay.tsx:82
     1  node_modules/react-native-maps/src/MapView.tsx:1041
```

### Reproducible sample code

```TSX
npx tsc
```

### Steps to reproduce

Install version 1.23.0.

### Expected result

No TypeScript errors.

### Actual result

Multiple TypeScript errors inside `node_modules` in the `react-native-maps` package (even though these should be ignored by TS).

### React Native Maps Version

1.23.0

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.76.9

### What version of Expo are you using?

SDK 52

### Device(s)

Any

**Comment by salah-ghanim** [comment]
[v1.23.5](https://github.com/react-native-maps/react-native-maps/releases/tag/v1.23.5) should fix it

but in general it's a config issue on your side, your typescript shouldn't be checking node_modules

**Comment by bitcrumb** [comment]
I still get errors after upgrading. This is due to `"noUncheckedIndexedAccess": true,` in my `tsconfig.json`. Because when I set that to false, the errors dissappear.

However I don't get why these errors pop up, since `node_modules` *is* in my `exclude`  list:

## TS config

This is my config:

```
{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "compileOnSave": true,
  "compilerOptions": {
    "incremental": true,
    "types": [
      "react-native",
      "jest"
    ],
    /**
     * We are using esnext instead of the default `es2019`.
     * (e.g. this provides the replaceAll method on strings)
     */
    "lib": [
      "esnext"
    ],
    /* Stricter config */
    "noErrorTruncation": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "noUncheckedIndexedAccess": true,
    "plugins": []
  },
  "exclude": [
    "jest/matchers", // TODO: Remove & properly fix errors
    "node_modules"
  ]
}

```

## Errors

```
> tsc

node_modules/react-native-maps/src/decorateMapComponent.ts:164:7 - error TS2322: Type 'NativeComponent<unknown> | undefined' is not assignable to type 'NativeComponent<unknown>'.
  Type 'undefined' is not assignable to type 'NativeComponent<unknown>'.

164       return components[key];
          ~~~~~~

node_modules/react-native-maps/src/decorateMapComponent.ts:174:5 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

174     return UIManager.getViewManagerConfig(nativeComponentName).Commands[name];
        ~~~~~~

node_modules/react-native-maps/src/Geojson.tsx:388:5 - error TS2322: Type 'LatLng[] | undefined' is not assignable to type 'LatLng[]'.
  Type 'undefined' is not assignable to type 'LatLng[]'.

388     coordinates: coordinates[0],
        ~~~~~~~~~~~

  node_modules/react-native-maps/src/Geojson.tsx:532:3
    532   coordinates: LatLng[];
          ~~~~~~~~~~~
    The expected type comes from property 'coordinates' which is declared here on type 'Omit<AnyPolygonOverlay, "type">'

node_modules/react-native-maps/src/Geojson.tsx:394:3 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

394   latitude: c[1],
      ~~~~~~~~

  node_modules/react-native-maps/src/sharedTypes.ts:6:3
    6   latitude: number;
        ~~~~~~~~
    The expected type comes from property 'latitude' which is declared here on type 'LatLng'

node_modules/react-native-maps/src/Geojson.tsx:395:3 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

395   longitude: c[0],
      ~~~~~~~~~

  node_modules/react-native-maps/src/sharedTypes.ts:7:3
    7   longitude: number;
        ~~~~~~~~~
    The expected type comes from property 'longitude' which is declared here on type 'LatLng'

node_modules/react-native-maps/src/MapOverlay.tsx:82:27 - error TS2532: Object is possibly 'undefined'.

82     northEast: {latitude: bounds[0][0], longitude: bounds[0][1]},
                             ~~~~~~~~~

node_modules/react-native-maps/src/MapOverlay.tsx:82:52 - error TS2532: Object is possibly 'undefined'.

82     northEast: {latitude: bounds[0][0], longitude: bounds[0][1]},
                                                      ~~~~~~~~~

node_modules/react-native-maps/src/MapOverlay.tsx:83:27 - error TS2532: Object is possibly 'undefined'.

83     southWest: {latitude: bounds[1][0], longitude: bounds[1][1]},
                             ~~~~~~~~~

node_modules/react-native-maps/src/MapOverlay.tsx:83:52 - error TS2532: Object is possibly 'undefined'.

83     southWest: {latitude: bounds[1][0], longitude: bounds[1][1]},
                                                      ~~~~~~~~~


Found 9 errors in 3 files.

Errors  Files
     2  node_modules/react-native-maps/src/decorateMapComponent.ts:164
     3  node_modules/react-native-maps/src/Geojson.tsx:388
     4  node_modules/react-native-maps/src/MapOverlay.tsx:82
```

**Comment by trooperandz** [comment]
I have been experiencing the same. According to ChatGPT, this is happening because `react-native-maps` is shipping raw `.tsx` files.  Due to this, TypeScript will not treat them as external modules (hence the explicit `exclude` not working as expected).

**Comment by trooperandz** [comment]
I'm still getting the same issue in version 1.23.7.
