### ISSUE TITLE
No interface method putMap(String;com/facebook/react/bridge/WritableMap;) in RegionChangeEvent.java (Update needed to work with 0.61.5 RN)

### ISSUE THREAD

**Issue by emmajam** [react-native-maps/react-native-maps#3237]
# Bug

```
java.lang.NoSuchMethodError: No interface method 
putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in base.apk)
at com.airbnb.android.react.maps.p.dispatch(RegionChangeEvent.java:9)
```

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 36.60 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.0, 28.0.3, 29.0.0, 29.0.2
      System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.7.1 => 2.8.3
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 0.26.1

## Steps To Reproduce

1. Upgrade to 0.61.5 of RN
2. Attempt to use latest version of RN Maps

Describe what you expected to happen:

1. Maps work fine.

**Comment by emmajam** [comment]
I thought this to be an issue with our project, but after further testing it is definitely caused by the RN version.

**Comment by WangXiaoxi** [comment]
> I thought this to be an issue with our project, but after further testing it is definitely caused by the RN version.

i have the same problem

**Comment by UtopiaHXM** [comment]
react-native-cli: 2.0.1
react-native: 0.59.10
also have the same problem

**Comment by ram95krishh** [comment]
"react": "16.11.0",
"react-native": "0.62.2"

I have the same problem, but the issue happens in one specific device only. Not sure if these findings would be helpful, just in case..

Example of one device where it works fine:
Device: Oneplus 6
Android version: 10
Oxygen OS Version: 10.3.3

One where it doesn't:
Device: Redmi Note 5 Pro
Android version: 8.1.0

**Comment by ganoch** [comment]
Same here, 

RN 0.61.5

```java
        WritableMap events = Arguments.createMap();
        WritableMap output = Arguments.createMap();
        output.putString("encodedString", "");
        output.putBoolean("success", condition);
        events.putMap("output", output); //fails here
```

`WritableMap` is child of `ReadableMap` so it should work just fine, am I missing something here?

**Comment by wyytzf** [comment]
It's probably you are using separate versions of the RN when compiling and running.
Try to compile the react-native-maps with the correct version of the RN.

**Comment by GUILLALAB** [comment]
I tried all React Native version > 0.60.0 , I still have this problem.
What change could solve that?
